name: Check H5P library version

on:
  - push
  - workflow_dispatch

jobs:
  check-h5p-library-version:
    runs-on: ubuntu-latest
    steps:
      - uses: boyum/is-h5p-library-updated-action@v1
        id: h5p-version-check

      - uses: thollander/actions-comment-pull-request@v1 # https://github.com/thollander/actions-comment-pull-request
        if: ${{ steps.h5p-version-check.is-ahead == 'false' }}
        with:
          message: |
            The library version was not updated.
            Current version: ${{ steps.h5p-version-check.current-version-formatted }}
            Main version: ${{ steps.h5p-version-check.main-version-formatted }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
