name: Check H5P library version

on:
  - push
  - workflow_dispatch

jobs:
  check-h5p-library-version:
    runs-on: ubuntu-latest
    steps:
      - uses: boyum/is-h5p-library-updated-action@v1
        id: h5p-version-check

      - run: echo '${{ steps.h5p-version-check.outputs.is-ahead }}'

      - uses: jwalton/gh-find-current-pr@v1 # https://github.com/jwalton/gh-find-current-pr
        id: findPrNumber

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1 # https://github.com/peter-evans/create-or-update-comment
        if: ${{ steps.h5p-version-check.outputs.is-ahead == 'false' }}
        with:
          issue-number: ${{ findPrNumber.outputs.number }}
          body: |
            The library version was not updated.

            Current version: ${{ steps.h5p-version-check.current-version-formatted }}
            Main version: ${{ steps.h5p-version-check.main-version-formatted }}
