name: Check H5P library version

on:
  - push
  - workflow_dispatch

jobs:
  check-h5p-library-version:
    runs-on: ubuntu-latest
    steps:
      - uses: boyum/is-h5p-library-updated-action@v1
        id: h5p-version-check

      - run: |
          echo '${{ steps.h5p-version-check.outputs.main-version }}'
          echo '${{ steps.h5p-version-check.outputs.current-version }}'

          echo '${{ steps.h5p-version-check.outputs.main-version-formatted }}'
          echo '${{ steps.h5p-version-check.outputs.current-version-formatted }}'

      - uses: jwalton/gh-find-current-pr@v1 # https://github.com/jwalton/gh-find-current-pr
        id: findPrNumber

      - name: Find Comment
        uses: peter-evans/find-comment@v1 # https://github.com/peter-evans/find-comment
        id: find-comment
        with:
          issue-number: ${{ steps.findPrNumber.outputs.number }}
          comment-author: github-actions[bot]
          body-includes: <!-- h5p-library-check -->

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1 # https://github.com/peter-evans/create-or-update-comment
        if: steps.h5p-version-check.outputs.is-ahead == 'false' && steps.find-comment.outputs.comment-id == ''
        with:
          issue-number: ${{ steps.findPrNumber.outputs.number }}
          body: |
            <!-- h5p-library-check -->
            The library version was not updated.

            Current version: ${{ steps.h5p-version-check.outputs.current-version-formatted }}
            Main version: ${{ steps.h5p-version-check.outputs.main-version-formatted }}

      - name: Update comment
        if: steps.h5p-version-check.outputs.is-ahead == 'false' && steps.find-comment.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            <!-- h5p-library-check -->
            The library version was not updated.

            Current version: ${{ steps.h5p-version-check.outputs.current-version-formatted }}
            Main version: ${{ steps.h5p-version-check.outputs.main-version-formatted }}
