name: Build and Deploy
on:
  push:
    branches:
      - feat/deployment-for-gh-pages
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ️
        uses: actions/checkout@v2.3.1
        with:
          ref: gh-pages
      - name: setup git config
        run: |
          # setup the username and email.
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Rebasing
        run: |
          git rebase upstream main && git push --force
      - name: Install and Build
        run: |
          npm install
          npm run build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: storybook-static
          CLEAN: true
          TARGET_FOLDER: docs
